### ISSUE TITLE
Finding first blocked date between daterange

### ISSUE THREAD

**Issue by revati** [sharetribe/ftw-daily#1260]
**Describe the bug** A clear and concise description of what the bug is.
https://github.com/sharetribe/ftw-daily/blob/master/src/components/FieldDateRangeInput/DateRangeInput.helpers.js#L39

It doesn't check/skips first day. So if first day is missing in timeslots, it still will return that daterange isn't blocked.

**To Reproduce** Steps to reproduce the behavior:

Pass to `firstBlockedBetween` function 
- list of timeslots (from 2nd to 5th march)
- from date: (1st march)
- to date: (5th march)

**Expected behavior** A clear and concise description of what you expected to happen.
It should mark 1st march as blocked date, as it isn't present in timeslots.

**Additional context** Add any other context about the problem here.

Maybe im missing full scope of what this function does, but this quick fix (increasing start date only on recursive call) fixed issue for me.

```
const firstBlockedBetween = (timeSlots, startDate, endDate) => {
  if (moment(startDate).isSame(endDate, 'date')) {
    return null;
  }

  return timeSlotsContain(timeSlots, startDate)
    ? firstBlockedBetween(timeSlots, moment(startDate).add(1, 'days'), endDate)
    : startDate;
};
```

**Comment by Gnito** [comment]
Good point! 

My guess (without checking too much code) is that start date and end date are directly selected from DateRangePicker and its **isDayBlocked** function should keep it impossible for anyone to pick date-range, where start-date is not selectable.

That being said, it doesn't hurt to update the function if there are more use cases for it. Do you want to make a pull request?

**Comment by Gnito** [comment]
The current function definition mentions that both start and end are exclusive in this utility function. I'm finding it a bit hard to reserve time to make the change and go through testing in all the places that use that function. 

So, I'm closing this issue for now. We can open this later if there's a new development in the matter. Personally, I think there are quite many possibilities for bigger refactoring/improvements related to these util-functions and components that use them.
