### ISSUE TITLE
yarn run dev  is not working

### ISSUE THREAD

**Issue by MHamzaRajput** [sharetribe/ftw-daily#1330]
D:\ftw-daily>yarn run dev   
yarn run v1.22.4
$ yarn run config-check&&export NODE_ENV=development REACT_APP_DEV_API_SERVER_PORT=3500&&concurrently --kill-others "yarn run dev-frontend" "yarn run dev-backend"
$ node scripts/config.js --check
'export' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

D:\ftw-daily>yarn run dev

**Comment by priusGit** [comment]
In package .json line 93 "dev" and 102 "dev-server" change "export" to "set" - worked for me.
https://github.com/thechutrain/mern-passport/issues/3

**Comment by priusGit** [comment]
In **package.json** line 95: **"dev"** and line 104 **"dev-sever"** change "export" to **"set"**.  
Your **line 95** should look like:  
`"dev": "yarn run config-check&&set NODE_ENV=development REACT_APP_DEV_API_SERVER_PORT=3500&&concurrently --kill-others \"yarn run dev-frontend\" \"yarn run dev-backend\"",  `
and **line 104** should look like:  
`"dev-server": "set NODE_ENV=development PORT=4000 REACT_APP_CANONICAL_ROOT_URL=http://localhost:4000&&yarn run build&&nodemon --watch server server/index.js",  `
  
Worked perfectly to me.
https://github.com/thechutrain/mern-passport/issues/3

**Comment by Gnito** [comment]
Yeah, FTW templates are mainly made for Unix-like operating systems, since most host services are on top of Linux or something similar. 

"**export**" works in those environments to set environment variables, whereas DOS would need "set".

So, you should be able to get node app working by making the suggested change. However, I strongly recommend that you install [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

For example, our documentation also assumes Unix-like commands instead of DOS commands. 

Anyway, I'll add a ticket to our system that we should add a note about this issue to our repos.

**Comment by Gnito** [comment]
We decided to settle with adding an extra note to README.md. 
Closing this for now.

**Comment by casaltenburg** [comment]
![image](https://user-images.githubusercontent.com/23700968/104226935-df8efa80-5448-11eb-8e3f-0822dbc3b783.png)

Followed all the steps but the "yarn run dev"  command failed. Maybe i need an other version of the "jose" package?
I'm working on Windows 10, is Linux really necessary?

**Comment by Buymina** [comment]
I am a windows user, I have the same issue on "PRODUCT", not "DAILY"


![image](https://user-images.githubusercontent.com/94096753/141402168-3319a575-bf27-48fd-8f5a-1251fb42ffe3.png)

As suggested above, I changed the 'export' to 'set' in the package.json (different line numbers) but nothing happened. 

![image](https://user-images.githubusercontent.com/94096753/141402346-fafdfd32-844f-4224-a2ef-7b1eb648272f.png)

**Comment by aquilinoFrancisco** [comment]
> **If you are a Windows user** In your ftw-daily folder find file **package.json** line 95: **"dev"** and line 104 **"dev-sever"** change "export" to **"set"**. Your **line 95** should look like: `"dev": "yarn run config-check&&set NODE_ENV=development REACT_APP_DEV_API_SERVER_PORT=3500&&concurrently --kill-others \"yarn run dev-frontend\" \"yarn run dev-backend\"", ` and **line 104** should look like: `"dev-server": "set NODE_ENV=development PORT=4000 REACT_APP_CANONICAL_ROOT_URL=http://localhost:4000&&yarn run build&&nodemon --watch server server/index.js", `
> 
> Worked perfectly to me, cheers. [thechutrain/mern-passport#3](https://github.com/thechutrain/mern-passport/issues/3)

it worked for me

**Comment by bloddycrocodile** [comment]
I have a issue
please help
![img (4)](https://user-images.githubusercontent.com/110161438/184542926-f7b7b7b9-2adf-424f-b1e1-0ea901300f60.png)
