### ISSUE TITLE
Misordered CSS causes SelectSingleFilterPopup buttons look glitch

### ISSUE THREAD

**Issue by 3wnbr1** [sharetribe/ftw-daily#1352]
**Describe the bug**

CSS group style for `.menuLabel, .menuLabelSelected` is declared previous individual elements and therefore gets overridden. This bug was introduced in #1349

**To Reproduce** Steps to reproduce the behavior:

Run any ftw-daily with a `SelectSingleFilterPopup` enabled

**Screenshots**
<img width="287" alt="Screen Shot 2020-08-19 at 4 31 28 PM" src="https://user-images.githubusercontent.com/28008852/90648880-5d542e80-e23a-11ea-8be9-9ddfbf7f0147.png">

**Desktop**:
* OS: macOS 10.15.6
* Browser : Safari : 13.x / 14.0 / Chrome 84.0.x

**Smartphone** :
* Device: iPhone SE (1st gen)
* OS: iOS 14 Developper Beta 4
* Browser : Safari
* Version : 14

**Patch**

Placing group rule after individual elements fixes the issue

```diff
diff --git a/src/components/SelectSingleFilter/SelectSingleFilterPopup.css b/src/components/SelectSingleFilter/SelectSingleFilterPopup.css
index b531595c..2527539b 100644
--- a/src/components/SelectSingleFilter/SelectSingleFilterPopup.css
+++ b/src/components/SelectSingleFilter/SelectSingleFilterPopup.css
@@ -8,17 +8,6 @@
   }
 }
 
-.menuLabel,
-.menuLabelSelected {
-  @apply --marketplaceSearchFilterLabelFontStyles;
-
-  padding: var(--marketplaceButtonSmallDesktopPadding);
-  width: auto;
-  height: auto;
-  min-height: 0;
-  border-radius: 4px;
-}
-
 .menuLabel {
   @apply --marketplaceButtonStylesSecondary;
 
@@ -43,6 +32,17 @@
   }
 }
 
+.menuLabel,
+.menuLabelSelected {
+  @apply --marketplaceSearchFilterLabelFontStyles;
+
+  padding: var(--marketplaceButtonSmallDesktopPadding);
+  width: auto;
+  height: auto;
+  min-height: 0;
+  border-radius: 4px;
+}
+
 .menuContent {
   margin-top: 7px;
   padding-top: 13px;
```

**Comment by Gnito** [comment]
@3wnbr1 thank you for reporting. This was fixed in [v6.3.1](https://github.com/sharetribe/ftw-daily/releases/tag/v6.3.1)
aka PR [#1353](https://github.com/sharetribe/ftw-daily/pull/1353)
