### ISSUE TITLE
Typo : TransactionPanel

### ISSUE THREAD

**Issue by 3wnbr1** [sharetribe/ftw-daily#1440]
Hi Sharetribe Team

I guess you probably have a typo here. No idea about the potential impact however
https://github.com/sharetribe/ftw-daily/blob/ce0607ac2f0d491f75c82fcc52874cba7e9ca042/src/components/TransactionPanel/PanelHeading.js#L16

**Comment by Gnito** [comment]
Thank you for reporting. This is fixed in https://github.com/sharetribe/ftw-daily/pull/1451
