### ISSUE TITLE
Yarn dev

### ISSUE THREAD

**Issue by 89itworld** [sharetribe/ftw-daily#1526]
Apples-MacBook-Air:calx apple$ yarn dev
yarn run v1.22.17
$ yarn && yarn env-check:common && yarn env-check:app-store 
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "@types/node@16.9.1" is incompatible with requested version "@types/node@^12.12.6"
warning Resolution field "@types/node@16.9.1" is incompatible with requested version "@types/node@^12.12.6"
warning Resolution field "@types/node@16.9.1" is incompatible with requested version "@types/node@^12.12.6"
success Already up-to-date.
$ turbo run post-install
• Packages in scope: @calcom/app-store, @calcom/app-store-cli, @calcom/applecalendar, @calcom/caldavcalendar, @calcom/cli_base__app_name, @calcom/config, @calcom/core, @calcom/dailyvideo, @calcom/docs, @calcom/ee, @calcom/emails, @calcom/embed-core, @calcom/embed-react, @calcom/embed-snippet, @calcom/example-app, @calcom/exchange2013calendar, @calcom/exchange2016calendar, @calcom/giphy, @calcom/googlecalendar, @calcom/googlevideo, @calcom/hubspotothercalendar, @calcom/huddle01video, @calcom/jitsivideo, @calcom/lib, @calcom/metamask, @calcom/office365calendar, @calcom/office365video, @calcom/prisma, @calcom/slackmessaging, @calcom/spacebooking, @calcom/stripe, @calcom/stripepayment, @calcom/swagger, @calcom/tandemvideo, @calcom/tsconfig, @calcom/types, @calcom/ui, @calcom/vital, @calcom/web, @calcom/zapier, @calcom/zoomvideo, WipeMyCal
• Running post-install in 42 packages
@calcom/prisma:post-install: cache hit, replaying output 30683b14ad22f716
@calcom/prisma:post-install: yarn run v1.22.17
@calcom/prisma:post-install: $ yarn generate-schemas
@calcom/prisma:post-install: $ prisma generate && prisma format
@calcom/prisma:post-install: Environment variables loaded from .env
@calcom/prisma:post-install: Prisma schema loaded from schema.prisma
@calcom/prisma:post-install: 
@calcom/prisma:post-install: ✔ Generated Prisma Client (3.14.0 | library) to ./../../node_modules/@prisma/client in 1.43s
@calcom/prisma:post-install: 
@calcom/prisma:post-install: ✔ Generated Zod Schemas (0.5.4) to ./zod in 1.31s
@calcom/prisma:post-install: You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
@calcom/prisma:post-install: ```
@calcom/prisma:post-install: import { PrismaClient } from '@prisma/client'
@calcom/prisma:post-install: const prisma = new PrismaClient()
@calcom/prisma:post-install: ```
@calcom/prisma:post-install: Prisma schema loaded from schema.prisma
@calcom/prisma:post-install: Formatted /Applications/XAMPP/xamppfiles/htdocs/calx/packages/prisma/schema.prisma in 529ms 🚀
@calcom/prisma:post-install: Done in 10.74s.

 Tasks:    1 successful, 1 total
Cached:    1 cached, 1 total
  Time:    874ms >>> FULL TURBO

$ husky install
husky - Git hooks installed
$ dotenv-checker --schema .env.example --env .env

[ DOTENV-CHECKER ] - Initializing checks for .env files consistency & sync...

📗 [ INFO ]  ✅ Schema file (.env.example) checked successfully
🚧 [ WARN ]  ⚠️  Environment file (.env) differs from .env.example

  !! Alert !! The following key is not present in the ".env.example" file:
               - LICENSE:'agree'
    
📗 [ INFO ]  ✅ Environment file (.env) updated successfully
$ dotenv-checker --schema .env.appStore.example --env .env.appStore

[ DOTENV-CHECKER ] - Initializing checks for .env files consistency & sync...

📗 [ INFO ]  ✅ Schema file (.env.appStore.example) checked successfully
📗 [ INFO ]  ✅ Environment file (.env.appStore) checked successfully
$ turbo run dev --scope="@calcom/web"
• Packages in scope: @calcom/web
• Running dev in 1 packages
@calcom/web:dev: cache bypass, force executing 097306220a527c94
@calcom/web:dev: $ run-p app-store:watch next:dev
@calcom/web:dev: $ yarn workspace @calcom/app-store-cli watch  --watch
@calcom/web:dev: $ next dev
@calcom/web:dev: ready - started server on 0.0.0.0:3000, url: http://localhost:3000
@calcom/web:dev: warning package.json: No license field
@calcom/web:dev: $ ts-node --transpile-only src/app-store.ts --watch --watch
@calcom/web:dev: error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
@calcom/web:dev: Error: Please set NEXTAUTH_SECRET
@calcom/web:dev:     at Object.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/calx/apps/web/next.config.js:17:41)
@calcom/web:dev:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
@calcom/web:dev:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
@calcom/web:dev:     at Module.load (internal/modules/cjs/loader.js:950:32)
@calcom/web:dev:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
@calcom/web:dev:     at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
@calcom/web:dev:     at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
@calcom/web:dev:     at async Loader.import (internal/modules/esm/loader.js:178:24)
@calcom/web:dev:     at async Object.loadConfig [as default] (/Applications/XAMPP/xamppfiles/htdocs/calx/node_modules/next/dist/server/config.js:68:36)
@calcom/web:dev:     at async NextServer.loadConfig (/Applications/XAMPP/xamppfiles/htdocs/calx/node_modules/next/dist/server/next.js:114:22)
@calcom/web:dev: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@calcom/web:dev: error Command failed with exit code 1.
@calcom/web:dev: ERROR: "next:dev" exited with 1.
@calcom/web:dev: error Command failed with exit code 1.
@calcom/web:dev: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@calcom/web:dev: Error: command finished with error: command (apps/web) yarn run dev exited (1)
command (apps/web) yarn run dev exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    3.869s 

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Gnito** [comment]
Can you describe what you are trying to achieve? 

I’m not familiar with the tech stack described in this error log - and nothing seems to be related to Flex templates (which are Node.js/Express applications - you can’t run them on top of Next.js without customizing them heavily).

**Comment by Gnito** [comment]
I'm closing this as I don't think this is about FTW templates.
