### ISSUE TITLE
`sharetribe-scripts v6.0` and `GENERATE_SOURCEMAP=false`

### ISSUE THREAD

**Issue by anh-dinh-jh** [sharetribe/ftw-daily#1543]
**Describe the bug** 

On the new templates using **sharetribe-scripts v6.0**, set `GENERATE_SOURCEMAP = false`, got an error: 

```
create-react-app config structure changed, please check webpack.config.js and update to use the changed config
```

**To Reproduce** Steps to reproduce the behavior:

1. Set `GENERATE_SOURCEMAP = false` 
2. Run command `yarn dev` or `yarn build`
3. See error

**Expected behavior**

No errors

**Reasons**

**sharetribe-scripts v6.0**:

File: `packages/react-scripts/config/sharetribeWebpackConfig.js`

`hasRules` is false, which causes the `configStructureKnown` is false and then throws an error.

```
  const hasRules =
      config &&
      config.module &&
      config.module.rules &&
      config.module.rules.length === 2;
    
  ...

  const configStructureKnown = hasRules
        && hasOneOf
        && hasCssLoader
        && hasPlugins
        && hasOutput
        && hasOptimization;

  if (!configStructureKnown) {
    throw new Error(
      'create-react-app config structure changed, please check webpack.config.js and update to use the changed config'
    );
  }
```

**Changes on FB react-scripts** 
PR: [This](https://github.com/sharetribe/create-react-app/commit/359bfd71ee4c080d15fb44ab9c7f3ce5419fa808)
**react-scripts PR**: [This](https://github.com/facebook/create-react-app/commit/382ba21052ffd1321f3e7bb1dcb70d442106dff1)

File: `packages/react-scripts/config/webpack.config.js`
Changes: 
```
[
  // Handle node_modules packages that contain sourcemaps
  shouldUseSourceMap && {
    enforce: 'pre',
    exclude: /@babel(?:\/|\\{1,2})runtime/,
    test: /\.(js|mjs|jsx|ts|tsx|css)$/,
    loader: require.resolve('source-map-loader'),
  },
  ...
].filter(Boolean)
```

With this change: `GENERATE_SOURCEMAP = false` --> `shouldUseSourceMap` is false --> `config.module.rules.length` is 1 --> `config.module.rules.length===2` is false -->  `configStructureKnown` is false and then throws an error.

**Comment by Gnito** [comment]
Now the sharetribe-scripts v6.0.1 is released and taken into use on the master branch of FTW-daily.
