### ISSUE TITLE
`sharetribe-scripts v6.0` and webpack5 optimization config

### ISSUE THREAD

**Issue by anh-dinh-jh** [sharetribe/ftw-daily#1545]
**Describe the bug** Got error: ``` routeConfiguration is not a function ```

**To Reproduce** Steps to reproduce the behavior:

1. Set `async` to any thunk in *.duck.js, for example: `searchListings` in `SearchPage.duck.js`
2. Run `yarn build` or `yarn dev-server`
3. See error

<img width="610" alt="image" src="https://user-images.githubusercontent.com/80231759/185356383-6b0081bd-88a4-4583-bc81-577f444cebd5.png">

**Expected behavior** It should work normally as expected

**Causes** In CRA v5.0, FB had already deleted the `splitChunks` part. Then that part was added again in [this PR](https://github.com/sharetribe/create-react-app/commit/42a5d23eb58f92d368da63977d942e4cab76b1cc), which causes an error. Because by using webpack5.0, whenever we put `async` before any thunk, the `main` file will be split into 2 files 210.\*.js and main.\*.js. The `210` is placed before the `main` and then `loadable-server` - `requireEntrypoint` could only get the first one (210) to build.

<img width="353" alt="image" src="https://user-images.githubusercontent.com/80231759/185355767-89380867-85d8-4d66-ba77-b5223d0e225b.png">

**Possible solutions** 
- Change `splitChunks` from `all` to `async`
![image](https://user-images.githubusercontent.com/80231759/185354666-b91b8943-f4b4-4da4-a485-c65dbfa5163b.png)

- Add the property `name` and value `main`
![image](https://user-images.githubusercontent.com/80231759/185354514-16bfd2ff-1803-4cd0-bd9a-602171fc9d4c.png)

- Remove it again and make it as same as default

**Comment by Gnito** [comment]
Now the sharetribe-scripts v6.0.1 is released and taken into use on the master branch of FTW-daily.

**Comment by Gnito** [comment]
A new release is made with the updated sharetribe-scripts.
I'm closing this issue.
